// core/assets/vue/components/form/FormStatusMessage.vue
<template>
  <div v-if="message" :class="containerClass" :role="role">
    <p class="font-medium">
      <slot name="message">
        {{ message }}
      </slot>
    </p>
    <p v-if="description" class="mt-1 text-xs" :class="descriptionClass">
      <slot name="description">
        {{ description }}
      </slot>
    </p>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

type FormStatusKind = 'success' | 'error' | 'info';

const props = defineProps<{
  kind: FormStatusKind;
  messageKey?: string;
  message?: string;
  descriptionKey?: string;
}>();

const { t } = useI18n();

const styleMap: Record<FormStatusKind, { border: string; background: string; text: string; description: string }> = {
  success: {
    border: 'border-emerald-400',
    background: 'bg-emerald-50',
    text: 'text-emerald-900',
    description: 'text-emerald-700',
  },
  error: {
    border: 'border-destructive/40',
    background: 'bg-destructive/10',
    text: 'text-destructive',
    description: 'text-destructive',
  },
  info: {
    border: 'border-primary/40',
    background: 'bg-primary/10',
    text: 'text-primary',
    description: 'text-primary/80',
  },
};

const message = computed(() => {
  if (props.messageKey) {
    return String(t(props.messageKey));
  }
  if (props.message) {
    return String(props.message);
  }
  return '';
});
const description = computed(() => (props.descriptionKey ? String(t(props.descriptionKey)) : ''));

const kind = computed<FormStatusKind>(() => props.kind);
const kindStyles = computed(() => styleMap[kind.value]);

const containerClass = computed(() => {
  const styles = kindStyles.value;
  return ['rounded-lg border px-4 py-3 text-sm', styles.border, styles.background, styles.text].join(' ');
});

const descriptionClass = computed(() => kindStyles.value.description);

const role = computed(() => (kind.value === 'error' ? 'alert' : 'status'));
</script>

// webfront/src/app/shared/components/form-status-message/form-status-message.component.ts
import { Component, Input } from '@angular/core';
import { TranslateModule, TranslateService } from '@ngx-translate/core';

type FormStatusKind = 'success' | 'error' | 'info';

@Component({
  selector: 'app-form-status-message',
  templateUrl: './form-status-message.component.html',
  standalone: true,
  imports: [TranslateModule],
})
export class FormStatusMessageComponent {
  @Input() kind: FormStatusKind = 'info';
  @Input() messageKey?: string;
  @Input() message?: string;
  @Input() descriptionKey?: string;

  constructor(private readonly translate: TranslateService) {}

  get resolvedMessage(): string {
    if (this.messageKey) {
      return this.translate.instant(this.messageKey);
    }
    return this.message?.trim() ?? '';
  }

  get resolvedDescription(): string {
    if (this.descriptionKey) {
      return this.translate.instant(this.descriptionKey);
    }
    return '';
  }

  get containerClass(): string {
    const base = 'rounded-lg border px-4 py-3 text-sm';
    const styles = this.kindStyles;
    return [base, styles.border, styles.background, styles.text].join(' ');
  }

  get descriptionClass(): string {
    return this.kindStyles.description;
  }

  get role(): string {
    return this.kind === 'error' ? 'alert' : 'status';
  }

  private get kindStyles(): { border: string; background: string; text: string; description: string } {
    switch (this.kind) {
      case 'success':
        return {
          border: 'border-emerald-400',
          background: 'bg-emerald-50',
          text: 'text-emerald-900',
          description: 'text-emerald-700',
        };
      case 'error':
        return {
          border: 'border-destructive/40',
          background: 'bg-destructive/10',
          text: 'text-destructive',
          description: 'text-destructive',
        };
      case 'info':
      default:
        return {
          border: 'border-primary/40',
          background: 'bg-primary/10',
          text: 'text-primary',
          description: 'text-primary/80',
        };
    }
  }
}

@if (resolvedMessage) {
  <div [class]="containerClass" [attr.role]="role">
    <p class="font-medium">
      {{ resolvedMessage }}
    </p>
    @if (resolvedDescription) {
      <p class="mt-1 text-xs" [class]="descriptionClass">
        {{ resolvedDescription }}
      </p>
    }
  </div>
}
