// webfront/src/app/modules/auth/pages/invite-complete/invite-complete.component.ts
import { NgClass, NgFor, NgIf } from '@angular/common';
import { Component, DestroyRef, effect } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { AngularSvgIconModule } from 'angular-svg-icon';
import { ButtonComponent } from '../../../../shared/components/button/button.component';
import { AuthService } from '../../../../core/services/auth.service';
import { toSignal } from '@angular/core/rxjs-interop';
import { FormStatusMessageComponent } from '../../../../shared/components/form-status-message/form-status-message.component';
import { FrontendConfigService } from '../../../../core/services/frontend-config.service';
import { estimatePasswordStrength } from '../../../../core/utils/password-strength.util';
import { matchControlValidator, passwordStrengthValidator } from '../../utils/password-validators.util';
import { applyFieldErrors, INVITE_ERROR_MESSAGES, resolveApiErrorMessage, REGISTER_ERROR_MESSAGES } from '../../utils/auth-errors.util';
import { HttpErrorResponse } from '@angular/common/http';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';

@Component({
  selector: 'app-invite-complete',
  templateUrl: './invite-complete.component.html',
  styleUrls: ['./invite-complete.component.css'],
  imports: [ReactiveFormsModule, ButtonComponent, NgIf, NgClass, NgFor, AngularSvgIconModule, FormStatusMessageComponent],
})
export class InviteCompleteComponent {
  form: FormGroup;
  submitted = false;
  isSubmitting = false;
  passwordStrength = 0;
  passwordVisible = false;
  invitedEmail = '';
  alreadyCompleted = false;
  inviteExpired = false;
  private inviteToken = '';
  returnUrl: string | null = null;
  apiFieldErrors: Partial<Record<'password' | 'confirmPassword', string>> = {};
  status = {
    errorMessage: '',
    successMessage: '',
  };
  private readonly queryParamMap = toSignal(this.route.queryParamMap, { initialValue: this.route.snapshot.queryParamMap });

  constructor(
    private readonly formBuilder: FormBuilder,
    private readonly authService: AuthService,
    private readonly router: Router,
    private readonly route: ActivatedRoute,
    private readonly configService: FrontendConfigService,
    private readonly destroyRef: DestroyRef,
  ) {
    this.form = this.formBuilder.group({
      password: ['', Validators.required],
      confirmPassword: ['', Validators.required],
    });

    effect(() => {
      const params = this.queryParamMap();
      this.inviteToken = params.get('token') ?? '';
      this.returnUrl = params.get('returnUrl');

      if (this.inviteToken) {
        void this.loadInvitePreview(this.inviteToken);
      }
    });

    effect(() => {
      const minScore = this.configService.config().passwordStrengthLevel;
      const passwordControl = this.form.get('password');
      const confirmControl = this.form.get('confirmPassword');

      passwordControl?.setValidators([Validators.required, passwordStrengthValidator(minScore)]);
      confirmControl?.setValidators([Validators.required, matchControlValidator('password')]);
      passwordControl?.updateValueAndValidity({ emitEvent: false });
      confirmControl?.updateValueAndValidity({ emitEvent: false });
    });

    this.form
      .get('password')
      ?.valueChanges.pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((value) => {
        const passwordValue = typeof value === 'string' ? value : '';
        this.passwordStrength = estimatePasswordStrength(passwordValue);
        this.form.get('confirmPassword')?.updateValueAndValidity({ emitEvent: false });
      });
  }

  get f() {
    return this.form.controls;
  }

  get hasToken(): boolean {
    return this.inviteToken.trim().length > 0;
  }

  togglePasswordVisibility(): void {
    this.passwordVisible = !this.passwordVisible;
  }

  async onSubmit(): Promise<void> {
    this.submitted = true;
    this.status.errorMessage = '';
    this.status.successMessage = '';
    this.apiFieldErrors = {};

    if (this.form.invalid) {
      return;
    }

    if (!this.inviteToken) {
      this.status.errorMessage = INVITE_ERROR_MESSAGES['INVALID_INVITATION'];
      return;
    }

    const { password, confirmPassword } = this.form.value;

    this.isSubmitting = true;

    try {
      await this.authService.inviteComplete(this.inviteToken, password, confirmPassword);
      this.status.successMessage = 'Invitation confirmée. Vous pouvez vous connecter.';
      window.setTimeout(() => {
        const queryParams: { status?: string; returnUrl?: string } = { status: 'invited' };
        if (this.returnUrl) {
          queryParams.returnUrl = this.returnUrl;
        }
        void this.router.navigate(['/login'], { queryParams, replaceUrl: true });
      }, 1200);
    } catch (error) {
      this.handleError(error);
    } finally {
      this.isSubmitting = false;
    }
  }

  private async loadInvitePreview(token: string): Promise<void> {
    try {
      const preview = await this.authService.invitePreview(token);
      this.invitedEmail = preview.email ?? '';
      this.alreadyCompleted = preview.accepted ?? false;
      this.inviteExpired = preview.expired ?? false;

      if (this.alreadyCompleted) {
        this.status.successMessage =
          'Ce lien a déjà été utilisé et votre compte est activé. Vous pouvez vous connecter avec vos identifiants.';
      }

      if (this.inviteExpired) {
        this.status.errorMessage = INVITE_ERROR_MESSAGES['INVITATION_EXPIRED'];
      }
    } catch {
      // Silence: on laisse la validation se faire au submit.
    }
  }

  private handleError(error: unknown): void {
    if (error instanceof HttpErrorResponse) {
      const payload = (error.error ?? null) as { error?: string; message?: string; details?: Record<string, string> } | null;
      const fieldApplied = applyFieldErrors(
        payload,
        REGISTER_ERROR_MESSAGES,
        { plainPassword: 'password' },
        (field, message) => {
          this.apiFieldErrors[field as 'password' | 'confirmPassword'] = message;
        },
        'password',
      );
      if (!fieldApplied) {
        this.status.errorMessage =
          resolveApiErrorMessage(payload, INVITE_ERROR_MESSAGES) ?? INVITE_ERROR_MESSAGES['UNKNOWN'];
      }
      return;
    }

    this.status.errorMessage = INVITE_ERROR_MESSAGES['UNKNOWN'];
  }

  goToLogin(): void {
    void this.router.navigate(['/login'], { queryParams: this.returnUrl ? { returnUrl: this.returnUrl } : undefined });
  }
}

<form class="my-10 space-y-6" [formGroup]="form" (ngSubmit)="onSubmit()">
  <header class="space-y-2 text-center">
    <h2 class="text-foreground mb-1 text-3xl font-semibold">
      Complétez votre <span class="text-primary">compte</span>
    </h2>
    <p class="text-muted-foreground text-sm">
      Définissez votre profil et votre mot de passe pour activer votre accès.
    </p>
  </header>

  <app-form-status-message kind="error" [message]="status.errorMessage"></app-form-status-message>
  <app-form-status-message kind="success" [message]="status.successMessage"></app-form-status-message>

  <div *ngIf="alreadyCompleted" class="flex justify-center">
    <app-button impact="none" tone="primary" size="small" type="button" (buttonClick)="goToLogin()">
      Retour à la connexion
    </app-button>
  </div>

  <div *ngIf="!alreadyCompleted" class="space-y-3 text-left">
    <div class="form__group">
      <div class="form__field">
        <input id="invite-email" [value]="invitedEmail" class="form__input peer cursor-not-allowed opacity-70" type="email" placeholder=" " disabled />
        <label class="form__label" for="invite-email">Adresse email invitée</label>
      </div>
    </div>

    <div class="form__group">
      <div class="form__field">
        <input
          id="invite-password"
          [type]="passwordVisible ? 'text' : 'password'"
          autocomplete="new-password"
          class="form__input peer pr-12"
          placeholder=" "
          formControlName="password"
          [ngClass]="{ 'is__invalid-input': submitted && f['password'].errors }"
        />
        <label class="form__label" [ngClass]="{ 'peer-focus:text-destructive!': submitted && f['password'].errors }" for="invite-password">
          Mot de passe
        </label>
        <button
          type="button"
          class="form__toggle"
          aria-label="Afficher ou masquer le mot de passe"
          [attr.aria-pressed]="passwordVisible"
          (click)="togglePasswordVisibility()"
        >
          <svg-icon
            [src]="!passwordVisible ? 'assets/icons/heroicons/outline/eye-off.svg' : 'assets/icons/heroicons/outline/eye.svg'"
            [svgClass]="'h-5 w-5'"
          ></svg-icon>
        </button>
      </div>
      <p *ngIf="apiFieldErrors.password || (submitted && f['password'].errors)" class="is__invalid-error">
        <span *ngIf="apiFieldErrors.password">{{ apiFieldErrors.password }}</span>
        <span *ngIf="!apiFieldErrors.password && f['password'].errors?.['weakPassword']">Mot de passe invalide.</span>
        <span *ngIf="!apiFieldErrors.password && f['password'].errors?.['required']">Identifiants requis.</span>
      </p>
      <div class="mt-3 grid grid-cols-4 gap-2">
        <span
          *ngFor="let index of [1, 2, 3, 4]"
          [ngClass]="passwordStrength >= index ? 'bg-primary' : 'bg-border/80'"
          class="h-1 rounded-xs transition"
        ></span>
      </div>
      <p class="mt-2 text-xs text-muted-foreground">
        Choisissez un mot de passe robuste mélangeant lettres, chiffres et symboles.
      </p>
    </div>

    <div class="form__group">
      <div class="form__field">
        <input
          id="invite-confirm-password"
          type="password"
          autocomplete="new-password"
          class="form__input peer"
          placeholder=" "
          formControlName="confirmPassword"
          [ngClass]="{ 'is__invalid-input': submitted && f['confirmPassword'].errors }"
        />
        <label class="form__label" [ngClass]="{ 'peer-focus:text-destructive!': submitted && f['confirmPassword'].errors }" for="invite-confirm-password">
          Confirmez le mot de passe
        </label>
      </div>
      <p *ngIf="apiFieldErrors.confirmPassword || (submitted && f['confirmPassword'].errors)" class="is__invalid-error">
        <span *ngIf="apiFieldErrors.confirmPassword">{{ apiFieldErrors.confirmPassword }}</span>
        <span *ngIf="!apiFieldErrors.confirmPassword && f['confirmPassword'].errors?.['mismatch']">
          Les mots de passe ne correspondent pas.
        </span>
        <span *ngIf="!apiFieldErrors.confirmPassword && f['confirmPassword'].errors?.['required']">Identifiants requis.</span>
      </p>
    </div>
  </div>

  <div *ngIf="!alreadyCompleted">
    <app-button full impact="bold" tone="primary" shape="rounded" size="medium" [loading]="isSubmitting" [disabled]="!hasToken">
      Activer mon compte
    </app-button>
  </div>
</form>

// assets/vue/pages/Auth/Invite/InviteComplete.vue
<template>
  <form class="my-10 space-y-6" novalidate @submit.prevent="onSubmit">
    <header class="space-y-2 text-center">
      <h2 class="text-foreground mb-1 text-3xl font-semibold">
        {{ t('auth.invite.view.heading') }}
        <span class="text-primary">{{ t('auth.invite.view.heading_suffix') }}</span>
      </h2>
      <p class="text-muted-foreground text-sm">
        {{ t('auth.invite.view.subtitle') }}
      </p>
    </header>

    <FormStatusMessage kind="error" :message-key="status.errorKey" :message="status.errorMessage" />
    <FormStatusMessage kind="success" :message-key="status.successKey" />

    <div v-if="alreadyCompleted" class="flex justify-center">
      <AppButton variant="ghost" size="sm" type="button" @click="goToLogin">
        {{ t('auth.invite.view.back_to_login') }}
      </AppButton>
    </div>

    <div v-if="!alreadyCompleted" class="space-y-3 text-left">
      <div class="form__group">
        <div class="form__field">
          <input
            id="invite-email"
            :value="invitedEmail"
            :class="[inputClass(false), 'cursor-not-allowed opacity-70']"
            type="email"
            autocomplete="email"
            placeholder=" "
            disabled
          />
          <label :class="labelClass(false)" for="invite-email">
            {{ t('auth.invite.view.email_label') }}
          </label>
        </div>
      </div>

      <div class="form__group">
        <div class="form__field">
          <input
            id="invite-display-name"
            v-model="form.displayName"
            :class="inputClass(submitted && v$.displayName.$invalid)"
            type="text"
            autocomplete="name"
            placeholder=" "
            :aria-invalid="submitted && v$.displayName.$invalid"
            required
          />
          <label :class="labelClass(submitted && v$.displayName.$invalid)" for="invite-display-name">
            {{ t('auth.invite.view.display_name_label') }}
          </label>
        </div>
        <p
          v-if="apiFieldErrors.displayName || (submitted && v$.displayName.$error)"
          :class="validationErrorClass"
        >
          <span v-if="apiFieldErrors.displayName">{{ t(apiFieldErrors.displayName!) }}</span>
          <span v-else>{{ t(REGISTER_ERROR_KEYS.DISPLAY_NAME_REQUIRED) }}</span>
        </p>
      </div>

      <div class="form__group">
        <div class="form__field">
          <input
            id="invite-password"
            v-model="form.password"
            :type="passwordInputType"
            :class="[inputClass(submitted && v$.password.$invalid), 'pr-12']"
            autocomplete="new-password"
            placeholder=" "
            :aria-invalid="submitted && v$.password.$invalid"
            required
          />
          <label :class="labelClass(submitted && v$.password.$invalid)" for="invite-password">
            {{ t('auth.invite.view.password_label') }}
          </label>
          <button
            type="button"
            class="form__toggle"
            :aria-label="t('auth.form.toggle_password')"
            :aria-pressed="passwordVisible"
            @click="togglePasswordVisibility"
          >
            <EyeSlashIcon v-if="!passwordVisible" class="h-5 w-5" aria-hidden="true" />
            <EyeIcon v-else class="h-5 w-5" aria-hidden="true" />
          </button>
        </div>
        <p v-if="apiFieldErrors.password || (submitted && v$.password.$error)" :class="validationErrorClass">
          <span v-if="apiFieldErrors.password">{{ t(apiFieldErrors.password!) }}</span>
          <span v-else>{{ t(REGISTER_ERROR_KEYS.INVALID_PASSWORD) }}</span>
        </p>
        <div class="mt-3 grid grid-cols-4 gap-2">
          <span
            v-for="index in 4"
            :key="index"
            :class="[
              'h-1 rounded-xs transition',
              passwordStrength >= index ? 'bg-primary' : 'bg-border/80',
            ]"
          />
        </div>
        <p class="mt-2 text-xs text-muted-foreground">
          {{ t('auth.register.view.password_hint') }}
        </p>
      </div>

      <div class="form__group">
        <div class="form__field">
          <input
            id="invite-confirm-password"
            v-model="form.confirmPassword"
            :class="inputClass(submitted && v$.confirmPassword.$invalid)"
            type="password"
            autocomplete="new-password"
            placeholder=" "
            :aria-invalid="submitted && v$.confirmPassword.$invalid"
            required
          />
          <label
            :class="labelClass(submitted && v$.confirmPassword.$invalid)"
            for="invite-confirm-password"
          >
            {{ t('auth.invite.view.confirm_password_label') }}
          </label>
        </div>
        <p
          v-if="apiFieldErrors.confirmPassword || (submitted && v$.confirmPassword.$error)"
          :class="validationErrorClass"
        >
          <span v-if="apiFieldErrors.confirmPassword">{{ t(apiFieldErrors.confirmPassword!) }}</span>
          <span v-else>{{ t(PASSWORD_MISMATCH_KEY) }}</span>
        </p>
      </div>
    </div>

    <div v-if="!alreadyCompleted">
      <AppButton full variant="primary" size="md" :disabled="loading || !hasToken">
        {{ t('auth.invite.view.submit') }}
      </AppButton>
    </div>
  </form>
</template>

<script setup lang="ts">
import { computed, reactive } from 'vue';
import { useI18n } from 'vue-i18n';
import { useVuelidate } from '@vuelidate/core';
import { helpers, minLength, required, sameAs } from '@vuelidate/validators';
import { EyeIcon, EyeSlashIcon } from '@heroicons/vue/24/outline';
import AppButton from '../../../components/AppButton.vue';
import FormStatusMessage from '../../../components/form/FormStatusMessage.vue';
import { useFormFieldClasses } from '../../../composables/useFormFieldClasses';
import { usePasswordVisibility } from '../../../composables/usePasswordVisibility';
import { usePasswordStrength } from '../../../composables/usePasswordStrength';
import { useSubmissionState } from '../../../composables/useSubmissionState';
import type { AuthEndpoints, AuthPages } from '../../../features/auth/types';
import { PASSWORD_MISMATCH_KEY, REGISTER_ERROR_KEYS } from '../../../features/auth/constants';
import { createAuthApi, AuthApiError } from '../../../features/auth/api';
import { useFormStatus } from '../../../features/auth/composables/useFormStatus';
import { useAuthNavigation } from '../../../features/auth/composables/useAuthNavigation';
import { handleApiError } from '../../../features/auth/composables/useApiErrors';
import { http, jsonConfig } from '../../../utils/http';

const props = defineProps<{
  endpoints: AuthEndpoints;
  pages: AuthPages;
  inviteToken: string;
  invitedEmail?: string | null;
  inviteAlreadyAccepted?: boolean;
}>();

interface InviteCompleteForm {
  displayName: string;
  password: string;
  confirmPassword: string;
}

const form = reactive<InviteCompleteForm>({
  displayName: '',
  password: '',
  confirmPassword: '',
});

const apiFieldErrors = reactive<Partial<Record<keyof InviteCompleteForm, string>>>({});

const { submitted, loading, markSubmitted, withLoading } = useSubmissionState();
const { status, setError, setSuccess, resetStatus } = useFormStatus();
const navigation = useAuthNavigation(props.pages);

const hasToken = computed(() => typeof props.inviteToken === 'string' && props.inviteToken.trim() !== '');
const invitedEmail = computed(() => props.invitedEmail ?? '');
const alreadyCompleted = computed(() => props.inviteAlreadyAccepted === true);

const passwordValue = computed(() => form.password);
const { passwordStrength } = usePasswordStrength(passwordValue);

const v$ = useVuelidate(
  {
    displayName: { required },
    password: { required, minLength: minLength(8) },
    confirmPassword: {
      required,
      sameAsPassword: sameAs(passwordValue),
    },
  },
  form,
);

const { inputClass, labelClass, validationErrorClass } = useFormFieldClasses();
const {
  visible: passwordVisible,
  inputType: passwordInputType,
  toggle: togglePasswordVisibility,
} = usePasswordVisibility();

const { t } = useI18n();

if (alreadyCompleted.value) {
  setSuccess('auth.invite.view.already_completed');
}

const clearFieldErrors = () => {
  Object.keys(apiFieldErrors).forEach((key) => {
    delete apiFieldErrors[key as keyof InviteCompleteForm];
  });
};

const handleError = (error: AuthApiError) => {
  handleApiError({
    payload: error.payload,
    translationMap: REGISTER_ERROR_KEYS,
    fallbackKey: 'common.error.unexpected',
    setError,
    fieldMap: {
      email: 'email',
      'identity.displayName': 'displayName',
      plainPassword: 'password',
    },
    defaultField: 'displayName',
    setFieldError: (field, key) => {
      apiFieldErrors[field as keyof InviteCompleteForm] = key;
    },
  });
};

const onSubmit = async () => {
  markSubmitted();
  resetStatus();
  clearFieldErrors();

  if (!hasToken.value) {
    setError('INVALID_INVITATION');
    return;
  }

  const isValid = await v$.value.$validate();

  if (!isValid) {
    return;
  }

  await withLoading(async () => {
    try {
      await http.post(
        '/api/auth/invite/complete',
        {
          token: props.inviteToken,
          displayName: form.displayName,
          password: form.password,
          confirmPassword: form.confirmPassword,
        },
        jsonConfig(true),
      );

      setSuccess('auth.register.message.success');

      window.setTimeout(() => {
        navigation.goToLogin();
      }, 1200);
    } catch (error) {
      const normalized = error instanceof AuthApiError ? error : new AuthApiError('Unexpected', { cause: error });
      handleError(normalized);
    }
  });
};

const goToLogin = () => {
  navigation.goToLogin();
};

</script>
