// assets/vue/pages/Auth/SignUp/SignUp.vue
<template>
  <AlreadyLog :redirect-target="props.redirectTarget">
    <form class="my-10 space-y-6" novalidate @submit.prevent="onSubmit">
      <div class="space-y-4">
        <div class="text-center">
          <h2 class="text-foreground mb-1 text-3xl font-semibold">
            {{ t('auth.register.view.heading') }}
            <span class="text-primary">{{ t('auth.register.view.heading_suffix') }}</span>
          </h2>
          <p class="text-muted-foreground text-sm">
            {{ t('auth.register.view.subtitle') }}
          </p>
        </div>
      </div>

      <FormStatusMessage
        kind="error"
        :message-key="status.errorKey"
        :message="status.errorMessage"
      />
      <FormStatusMessage kind="success" :message-key="status.successKey" />

      <div class="space-y-3 text-left">
        <div class="form__group">
          <div class="form__field">
            <input
              id="register-email"
              v-model="form.email"
              :class="inputClass(submitted && v$.email.$invalid)"
              type="email"
              inputmode="email"
              autocomplete="email"
              placeholder=" "
              :aria-invalid="submitted && v$.email.$invalid"
              required
            />
            <label :class="labelClass(submitted && v$.email.$invalid)" for="register-email">
              {{ t('auth.register.form.email.label') }}
            </label>
          </div>
          <p v-if="apiFieldErrors.email || (submitted && v$.email.$error)" :class="validationErrorClass">
            <span v-if="apiFieldErrors.email">{{ t(apiFieldErrors.email!) }}</span>
            <span v-else-if="v$.email.email.$invalid">{{ t('auth.login.error.api.INVALID_PAYLOAD') }}</span>
            <span v-else>{{ t('auth.login.error.credentials_required') }}</span>
          </p>
        </div>

        <div class="form__group">
          <div class="form__field">
            <input
              id="register-password"
              v-model="form.password"
              :type="passwordInputType"
              :class="[inputClass(submitted && v$.password.$invalid), 'pr-12']"
              autocomplete="new-password"
              placeholder=" "
              :aria-invalid="submitted && v$.password.$invalid"
              required
            />
            <label :class="labelClass(submitted && v$.password.$invalid)" for="register-password">
              {{ t('auth.register.form.password.label') }}
            </label>
            <button
              type="button"
              class="form__toggle"
              :aria-label="t('auth.form.toggle_password')"
              :aria-pressed="passwordVisible"
              @click="togglePasswordVisibility"
            >
              <EyeSlashIcon v-if="!passwordVisible" class="h-5 w-5" aria-hidden="true" />
              <EyeIcon v-else class="h-5 w-5" aria-hidden="true" />
            </button>
          </div>
          <p v-if="apiFieldErrors.password || (submitted && v$.password.$error)" :class="validationErrorClass">
            <span v-if="apiFieldErrors.password">{{ t(apiFieldErrors.password!) }}</span>
            <span v-else-if="v$.password.strongEnough?.$invalid">
              {{ t(REGISTER_ERROR_KEYS.INVALID_PASSWORD) }}
            </span>
            <span v-else>{{ t('auth.login.error.credentials_required') }}</span>
          </p>
          <div class="grid grid-cols-4 gap-2">
            <span
              v-for="index in 4"
              :key="index"
              :class="['h-1 rounded-xs transition', passwordStrength >= index ? 'bg-primary' : 'bg-muted']"
            />
          </div>
          <p class="text-muted-foreground text-xs">
            {{ t('auth.register.view.password_hint') }}
          </p>
        </div>

        <div class="form__group">
          <div class="form__field">
            <input
              id="register-confirm-password"
              v-model="form.confirmPassword"
              :class="inputClass(submitted && v$.confirmPassword.$invalid)"
              type="password"
              autocomplete="new-password"
              placeholder=" "
              :aria-invalid="submitted && v$.confirmPassword.$invalid"
              required
            />
            <label
              :class="labelClass(submitted && v$.confirmPassword.$invalid)"
              for="register-confirm-password"
            >
              {{ t('auth.register.view.confirm_password') }}
            </label>
          </div>
          <p
            v-if="apiFieldErrors.confirmPassword || (submitted && v$.confirmPassword.$error)"
            :class="validationErrorClass"
          >
            <span v-if="apiFieldErrors.confirmPassword">{{ t(apiFieldErrors.confirmPassword!) }}</span>
            <span v-else>{{ t('password.reset.error.mismatch') }}</span>
          </p>
        </div>
      </div>

      <div>
        <AppButton full variant="primary" size="md" :disabled="loading">
          {{ t('auth.register.form.submit') }}
        </AppButton>
      </div>

      <div class="text-muted-foreground flex items-center text-sm">
        <span>{{ t('auth.register.view.already') }}</span>
        <AppButton variant="ghost" size="sm" type="button" class="ml-2" @click="goToSignIn">
          {{ t('auth.register.view.sign_in') }}
        </AppButton>
      </div>
    </form>
  </AlreadyLog>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n';
import { EyeIcon, EyeSlashIcon } from '@heroicons/vue/24/outline';
import AppButton from '../../../components/AppButton.vue';
import AlreadyLog from '../../../components/auth/AlreadyLog.vue';
import FormStatusMessage from '../../../components/form/FormStatusMessage.vue';
import { useFormFieldClasses } from '../../../composables/useFormFieldClasses';
import { usePasswordVisibility } from '../../../composables/usePasswordVisibility';
import type { AuthEndpoints, AuthPages, PasswordPolicyConfig } from '../../../features/auth/types';
import { REGISTER_ERROR_KEYS } from '../../../features/auth/constants';
import { useSignUpForm } from '../../../features/auth/composables/useSignUpForm';

const props = defineProps<{
  endpoints: AuthEndpoints;
  pages: AuthPages;
  redirectTarget: string;
  passwordPolicy?: PasswordPolicyConfig | null;
  resetToken?: string;
}>();

const {
  form,
  passwordStrength,
  submitted,
  loading,
  v$,
  status,
  apiFieldErrors,
  onSubmit,
  goToSignIn,
} = useSignUpForm(props);

const { inputClass, labelClass, validationErrorClass } = useFormFieldClasses();
const {
  visible: passwordVisible,
  inputType: passwordInputType,
  toggle: togglePasswordVisibility,
} = usePasswordVisibility();

const { t } = useI18n();
</script>

// webfront/src/app/modules/auth/pages/sign-up/sign-up.component.ts
import { NgClass, NgIf } from '@angular/common';
import { Component, effect } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AngularSvgIconModule } from 'angular-svg-icon';
import { ButtonComponent } from 'src/app/shared/components/button/button.component';
import { AuthService } from '../../../../core/services/auth.service';
import { toSignal } from '@angular/core/rxjs-interop';

@Component({
  selector: 'app-sign-up',
  templateUrl: './sign-up.component.html',
  styleUrls: ['./sign-up.component.css'],
  imports: [ReactiveFormsModule, RouterLink, AngularSvgIconModule, ButtonComponent, NgIf, NgClass],
})
export class SignUpComponent {
  form: FormGroup;
  submitted = false;
  isSubmitting = false;
  errorMessage = '';
  returnUrl: string | null = null;
  private readonly queryParamMap = toSignal(this.route.queryParamMap, { initialValue: this.route.snapshot.queryParamMap });

  constructor(
    private readonly formBuilder: FormBuilder,
    private readonly authService: AuthService,
    private readonly router: Router,
    private readonly route: ActivatedRoute,
  ) {
    this.form = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required],
      confirmPassword: ['', Validators.required],
      acceptTerms: [false, Validators.requiredTrue],
    });

    effect(() => {
      this.returnUrl = this.queryParamMap().get('returnUrl');
    });
  }

  get f() {
    return this.form.controls;
  }

  async onSubmit(): Promise<void> {
    this.submitted = true;
    this.errorMessage = '';

    if (this.form.invalid) {
      return;
    }

    const { email, password, confirmPassword } = this.form.value;
    if (password !== confirmPassword) {
      this.errorMessage = 'Les mots de passe ne correspondent pas.';
      return;
    }

    this.isSubmitting = true;
    try {
      await this.authService.register(email, password);
      const queryParams: { status?: string; email?: string; returnUrl?: string } = {
        status: 'registered',
        email,
      };
      if (this.returnUrl) {
        queryParams.returnUrl = this.returnUrl;
      }
      void this.router.navigate(['/login'], { queryParams, replaceUrl: true });
    } catch {
      this.errorMessage = 'Inscription impossible. Vérifiez les informations.';
    } finally {
      this.isSubmitting = false;
    }
  }
}

<app-already-authenticated [redirectTarget]="redirectTarget">
  <form class="my-10 space-y-6" [formGroup]="form" (ngSubmit)="onSubmit()">
    <div class="space-y-4">
      <div class="text-center">
        <h2 class="text-foreground mb-1 text-3xl font-semibold">Créer un compte <span class="text-primary">!</span></h2>
        <p class="text-muted-foreground text-sm">Créez votre compte pour aller plus loin.</p>
      </div>
    </div>

    <app-form-status-message kind="error" [message]="status.errorMessage"></app-form-status-message>
    <app-form-status-message kind="success" [message]="status.successMessage"></app-form-status-message>

    <div class="space-y-3 text-left">
      <div class="form__group">
        <div class="form__field">
          <input
            id="register-email"
            type="email"
            inputmode="email"
            autocomplete="email"
            class="form__input peer"
            placeholder=" "
            formControlName="email"
            [ngClass]="{ 'is__invalid-input': submitted && f['email'].errors }"
          />
          <label class="form__label" [ngClass]="{ 'peer-focus:text-destructive!': submitted && f['email'].errors }" for="register-email">
            Adresse email
          </label>
        </div>
        @if (apiFieldErrors.email || (submitted && f['email'].errors)) {
          <p class="is__invalid-error">
            @if (apiFieldErrors.email) {
              <span>{{ apiFieldErrors.email }}</span>
            }
            @if (!apiFieldErrors.email && f['email'].hasError('email')) {
              <span>Adresse email invalide.</span>
            }
            @if (!apiFieldErrors.email && f['email'].hasError('required')) {
              <span>Adresse email requise.</span>
            }
          </p>
        }
      </div>

      <div class="form__group">
        <div class="form__field">
          <input
            id="register-password"
            [type]="passwordVisible ? 'text' : 'password'"
            autocomplete="new-password"
            class="form__input peer pr-12"
            placeholder=" "
            formControlName="password"
            [ngClass]="{ 'is__invalid-input': submitted && f['password'].errors }"
          />
          <label class="form__label" [ngClass]="{ 'peer-focus:text-destructive!': submitted && f['password'].errors }" for="register-password">
            Mot de passe
          </label>
          <button
            type="button"
            class="form__toggle"
            aria-label="Afficher ou masquer le mot de passe"
            [attr.aria-pressed]="passwordVisible"
            (click)="togglePasswordVisibility()"
          >
            <svg-icon
              [src]="!passwordVisible ? 'assets/icons/heroicons/outline/eye-off.svg' : 'assets/icons/heroicons/outline/eye.svg'"
              [svgClass]="'h-5 w-5'"
            ></svg-icon>
          </button>
        </div>
        @if (apiFieldErrors.password || (submitted && f['password'].errors)) {
          <p class="is__invalid-error">
            @if (apiFieldErrors.password) {
              <span>{{ apiFieldErrors.password }}</span>
            }
            @if (!apiFieldErrors.password && f['password'].hasError('weakPassword')) {
              <span>Mot de passe trop faible.</span>
            }
            @if (!apiFieldErrors.password && f['password'].hasError('required')) {
              <span>Mot de passe requis.</span>
            }
          </p>
        }
        <div class="grid grid-cols-4 gap-2">
          @for (index of [1, 2, 3, 4]; track index) {
            <span
              [ngClass]="passwordStrength >= index ? 'bg-primary' : 'bg-muted'"
              class="h-1 rounded-xs transition"
            ></span>
          }
        </div>
        <p class="text-muted-foreground text-xs">Choisissez un mot de passe robuste mélangeant lettres, chiffres et symboles.</p>
      </div>

      <div class="form__group">
        <div class="form__field">
          <input
            id="register-confirm-password"
            type="password"
            autocomplete="new-password"
            class="form__input peer"
            placeholder=" "
            formControlName="confirmPassword"
            [ngClass]="{ 'is__invalid-input': submitted && f['confirmPassword'].errors }"
          />
          <label class="form__label" [ngClass]="{ 'peer-focus:text-destructive!': submitted && f['confirmPassword'].errors }" for="register-confirm-password">
            Confirmez le mot de passe
          </label>
        </div>
        @if (submitted && f['confirmPassword'].errors) {
          <p class="is__invalid-error">
            @if (f['confirmPassword'].hasError('mismatch')) {
              <span>Les mots de passe ne correspondent pas.</span>
            }
            @if (f['confirmPassword'].hasError('required')) {
              <span>Confirmation requise.</span>
            }
          </p>
        }
      </div>
    </div>

    <div>
      <app-button full impact="bold" tone="primary" shape="rounded" size="medium" [loading]="isSubmitting">
        Créer mon compte
      </app-button>
    </div>

    <div class="text-muted-foreground flex items-center text-sm">
      Déjà un compte ?
      <app-button
        routerLink="/login"
        [queryParams]="returnUrl ? { returnUrl } : null"
        impact="none"
        tone="primary"
        shape="rounded"
        size="small"
      >
        Se connecter
      </app-button>
    </div>
  </form>
</app-already-authenticated>
